---
title: "assignment 03"
author: "Chenming Ran"
date: "2/13/2020"
output: html_document
---

```{r install-packages, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
install.packages("usmap",repos = "http://cran.us.r-project.org")
install.packages("scales", repos = "http://cran.us.r-project.org")
```

```{r load packaages, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
library(usmap)
library(ggplot2)
library(tidyverse)
library(haven)
library(scales)
```

```{r import data, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
trade <- read_stata("us_trade_data.dta")
trade$trade_type[trade$trade_type == "Total Exports"] <- "Export" 
trade$trade_type[trade$trade_type == "Total Imports"] <- "Import"
trade$year = as.character(trade$year)
head(trade,10)
```

```{r line graph, echo=TRUE, message=TRUE, warning=TRUE, paged.print=TRUE}
trade_1 <- trade %>%
  filter(is.na(trade_value) == FALSE) %>% 
  filter(country %in% c("Africa", "Asia", "Australia and Oceania", "Europe", "North America", "South/Central America" ))%>%
  group_by(year, trade_type) %>%
  summarize(trade_value = mean(trade_value)) %>%
  pivot_wider(id_cols = year, names_from = trade_type, values_from = trade_value) 
trade_1$Net_Import = trade_1$Import-trade_1$Export

ggplot(data = trade_1, aes(year,group = 1)) +
  geom_line(aes(y = Export/1000000,color = "darkred")) + 
  geom_line(aes(y = Import/1000000,color ="darkgreen")) +
  scale_colour_discrete(name  ="Trade Type",labels=c("Import", "Export")) +
  xlab("Year") +
  ylab("Average $ Million")+
  ggtitle("Graph 1: The U.S. Exports versus Imports") +
  theme(plot.title = element_text(hjust = 0.5))

# The Graph 1 shows the trend of U.S exports and imports from the year 2008 to the year 2019. It suggests that despite the sharp drop in 2008 and another low point in 2016, both exports and import have been steadily increasing until 2018. The country has experienced a relatively steeper increase quickly after recovering from the financial crisis in 2009, while other increases are relatively stable over time. Regarding the gap between two lines, it can be concluded that the trade deficit has been increasing over time, and the deficit has even increased since the 2016 election. This is definitely relevant to U.S.trade policy, which is always on the propoganda of Trump administration. The patterns of U.S. Exports and Imports, as well as the gap representing trade deficit, do not seem to show that U.S. has gained more surplus from trade since 2016. To note, Trump escalasted tarriffs on imports in 2018 but the pain appears on both exports and imports. 
```
```{r create area graph, echo=TRUE, message=TRUE, warning=TRUE, paged.print=TRUE}
trade_3 <- trade %>%
  filter(is.na(trade_value) == FALSE) %>% 
  filter(country %in% c("Africa", "Asia", "Australia and Oceania", "Europe", "North America", "South/Central America" ))%>%
  group_by(year, trade_type, country) %>%
  summarize(trade_value = mean(trade_value)) %>%
  pivot_wider(names_from = trade_type, values_from = trade_value) 
trade_3$year = as.numeric(trade_3$year)
trade_3$Net_Import = trade_3$Import-trade_3$Export

ggplot(data=trade_3, aes(x=year, y=Net_Import/1000000,  fill=country)) + 
    scale_x_discrete(limit = c(2008, 2011, 2015,2019), name = "Year") +
    ylab("Average $ Million") +
    scale_fill_discrete(name = "World Region") +
    ggtitle("Graph 2: The U.S. Net Imports by Region and over Time") +
    theme(plot.title = element_text(hjust = 0.5)) +
    geom_area()

# The Graph 2 further breaks down the trend of U.S trade deficit represented by net imports from the year 2008 to the year 2019. Taking into account 6 world regions as export destinations and import origins, the graph shows that the major deficits occurs from U.S. trade activities with Asian countries, secondly with Europe, Thirdly with North America. However, for its trade activities with Africa, Australia and South/Central America, there are rather trade surplus. This sort of explains Trump interests in Asian Pacific, specifically China as the major trade policy target. But this seems do not provide rationales for imposing tarriffs on goods from Brazil and Mexico in the year 2019 and for calling questions on NAFTA.
```

```{r bar graph, echo=TRUE, message=TRUE, warning=TRUE, paged.print=TRUE}
trade_2 <- trade %>%
  filter(is.na(trade_value) == FALSE, year == 2019) %>% 
  filter(country %in% c("China", "Canada", "Mexico", "Brazil", "Germany"))%>%
  group_by(country, trade_type) %>%
  summarize(trade_value = sum(trade_value)) 

ggplot(data=trade_2, aes(x= reorder(country, trade_value), y = trade_value/1000000000, fill = trade_type))+
    geom_bar(stat="identity",width = 0.6) +
    scale_fill_manual(name = "Trade Type", values= c('darkgreen','darkred') ) +
    scale_y_continuous(name = "Total $ Billion", breaks = seq(0, 3000, by = 100)) +
    xlab("Country") +
    ggtitle("Graph 3: The 2019 U.S.Trade Values by Related Regions")+
    theme(plot.title = element_text(hjust = 0.5)) +
    coord_flip() +
    theme_minimal()

#The Graph 3 takes a single year of 2019 to look at compare total trade values with major related countries. Trump has imposed a large amount of tarrifs last year, mainly regarding imports from China, but also from several places including Canada, Germany, Brazil, Mexico. However, the graph shows that China still accounts for its major imports, although the total trade value with China is below NAFTA countries. U.S. is exporting to Canada and Mexico a lot compared to its exports to China, given that NAFTA has allow many U.S.firms to export to Canada and Mexico mainly with higher-skilled goods. But such agreements do not exist with China and Germany.

```

```{r create map, echo=TRUE, message=TRUE, warning=TRUE, paged.print=TRUE}
trade_4 <- trade %>%
  filter(is.na(trade_value) == FALSE, year == c(2019)) %>% 
  filter(country %in% c("Africa", "Asia", "Australia and Oceania", "Europe", "North America", "South/Central America" ))%>%
  group_by(state,trade_type,year) %>%
  summarize(trade_value = sum(trade_value)) %>%
  pivot_wider(names_from = trade_type, values_from = trade_value) 
trade_4$Net_Import = trade_4$Import-trade_4$Export

#low = "#56B1F7", high = "#132B43" - default
plot_usmap(regions = "state", data = trade_4, values = "Net_Import", color = "black") + 
  scale_fill_continuous(low = "white", high = "darkblue", name = "Total Value", label=number_format(scale=1e-9, suffix = "billion"), limits=c(0,300000000000), breaks=seq(0,300000000000, by=50000000000)) + 
  ggtitle("The 2019 U.S.State Net-Imports") +
  theme(legend.position = "right", plot.title = element_text(hjust = 0.5))

#The Graph 4 also takes a single year of 2019 but to look at U.S net imports across all states. Cross-state trade patterns show that a few states are indeed exporting rather than importing goods, while many are still importing slightly more than exporting. The state with highest net imports is California, whose trade deficits significantly surpasses all other states, In contrast, the states marked with grey color export more than its imports. Since the country as a whole has large net imports, this implies that the difference in trade is huge among among different states. Importantly, more liberal states tend to have higher trade deficit, meaning higher net import, which can partly implies party affiliation pattern especially near election term.
```